// Port names from Naval Action game
export const naPortNames = [
  // Major ports and capitals
  "Port-au-Prince",
  "La Habana",
  "Kingston",
  "Cartagena",
  "Caracas",
  "Willemstad",
  "Gustavia",
  "Road Town",
  "Bridgetown",
  "Fort-de-France",
  "Pointe-à-Pitre",
  "Basse-Terre",
  "Roseau",
  "Castries",
  "Port of Spain",
  "George Town",
  "Nassau",
  "Marsh Harbour",
  "Port Royal",
  "Spanish Town",
  "Savannah",
  "Charleston",
  "Wilmington",
  "Norfolk",
  "Baltimore",
  "New York",
  "Boston",
  "Portsmouth",
  "Mortimer Town",
  "Shroud Cay",
  "Cockburn Town",
  "Clarence Town",
  "Great Harbour",
  "Colonel Hill",
  "Santo Domingo",
  "Santiago de Cuba",
  "Baracoa",
  "Puerto Príncipe",
  "Nuevitas",
  "Gibara",
  "Holguín",
  "Bayamo",
  "Manzanillo",
  "Cienfuegos",
  "Trinidad",
  "Batabanó",
  "Bahía Honda",
  "San Cristóbal",
  "Mariel",
  "Matanzas",
  "Cárdenas",
  "Sagua la Grande",
  "Remedios",
  "Santa Clara",
  "Puerto de Casilda",
  "Sancti Spíritus",
  "Morón",
  "Ciego de Ávila",
  "Las Tunas",
  "Puerto Padre",
  "Nuevitas del Príncipe",
  "Baría",
  "Guantánamo",
  "Santiago",
  "Cabo Cruz",
  "Manzanillo de Cuba",
  "Bayamo de Cuba",
  "Holguín de Cuba",
  "Gibara de Cuba",
  "Puerto Príncipe de Cuba",
  "Nuevitas de Cuba",
  "Baracoa de Cuba",
  "Cap-Français",
  "Fort-Dauphin",
  "Port-de-Paix",
  "Saint-Marc",
  "Gonaïves",
  "Léogâne",
  "Petit-Goâve",
  "Aux Cayes",
  "Jérémie",
  "Tiburon",
  "Dame-Marie",
  "Pestel",
  "Corail",
  "Roseaux",
  "Anse-d'Hainault",
  "Les Irois",
  "Tortuga",
  "Île de la Tortue",
  "San Juan",
  "Ponce",
  "Mayagüez",
  "Arecibo",
  "Aguadilla",
  "San Germán",
  "Guayama",
  "Humacao",
  "Fajardo",
  "Carolina",
  "Bayamón",
  "Toa Baja",
  "Manatí",
  "Vega Baja",
  "Camuy",
  "Quebradillas",
  "Isabela",
  "Moca",
  "San Sebastián",
  "Lares",
  "Las Marías",
  "Maricao",
  "Hormigueros",
  "Cabo Rojo",
  "Lajas",
  "Guánica",
  "Yauco",
  "Peñuelas",
  "Ponce Puerto Rico",
  "Juana Díaz",
  "Santa Isabel",
  "Salinas",
  "Coamo",
  "Aibonito",
  "Cayey",
  "Cidra",
  "Aguas Buenas",
  "Caguas",
  "Gurabo",
  "San Lorenzo",
  "Juncos",
  "Las Piedras",
  "Yabucoa",
  "Maunabo",
  "Patillas",
  "Arroyo",
  "Guayama Puerto Rico",
  "Belize",
  "Omoa",
  "Trujillo",
  "La Ceiba",
  "Puerto Cortés",
  "San Pedro Sula",
  "Tegucigalpa",
  "Comayagua",
  "Choluteca",
  "Puerto Lempira",
  "Puerto Cabezas",
  "Bluefields",
  "San Juan del Norte",
  "San Juan del Sur",
  "Corinto",
  "León",
  "Managua",
  "Granada",
  "Masaya",
  "Carazo",
  "Rivas",
  "Costa Rica",
  "Puntarenas",
  "San José",
  "Cartago",
  "Limón",
  "Puerto Viejo",
  "Panamá",
  "Colón",
  "Portobelo",
  "Nombre de Dios",
  "Santa María",
  "Penonomé",
  "Aguadulce",
  "Chitré",
  "Las Tablas",
  "Pedasí",
  "Tonosí",
  "Los Santos",
  "Macaracas",
  "Divisa",
  "Santiago de Veraguas",
  "Soná",
  "Atalaya",
  "Mariato",
  "Montijo",
  "Puerto Mutis",
  "Puerto Armuelles",
  "David",
  "Alanje",
  "Bugaba",
  "Barú",
  "Puerto Balboa",
  "Ancón",
  "Río Hato",
  "Antón",
  "Natá",
  "Olá",
  "La Pintada",
  "Llano Grande",
  "Santa Fe",
  "San Francisco",
  "Remedios de Panamá",
  "La Chorrera",
  "Arraijan",
  "Puerto Caimito",
  "Chame",
  "San Carlos",
  "Nueva Gorgona",
  "Coronado",
  "El Valle",
  "Santa Clara de Panamá",
  "Río Mar",
  "Farallón",
  "Churuquita Grande",
  "Guararé",
  "Villa de Los Santos",
  "Pocrí",
  "Parita",
  "Santa María de Panamá",
  "Chitre de Panamá",
  "Pesé",
  "La Arena",
  "Puerto Escondido",
  "Ocú",
  "Las Minas",
  "Llano de Piedra",
  "Monagrillo",
  "Isla de Cañas",
  "Puerto Pilon",
  "Cañaveral",
  "La Palma",
  "Puerto Limón",
  "Puerto Obaldia",
  "Acandí",
  "Turbo",
  "Necoclí",
  "Arboletes",
  "San Juan de Urabá",
  "Apartadó",
  "Carepa",
  "Chigorodó",
  "Mutatá",
  "Dabeiba",
  "Frontino",
  "Abriaquí",
  "Cañasgordas",
  "Santa Fe de Antioquia",
  "Sopetrán",
  "San Jerónimo",
  "Liborina",
  "Sabanalarga",
  "Peque",
  "Ituango",
  "Toledo",
  "Valdivia",
  "Tarazá",
  "Cáceres",
  "Caucasia",
  "El Bagre",
  "Nechí",
  "Zaragoza",
  "Segovia",
  "Remedios de Antioquia",
  "Amalfi",
  "Vegachí",
  "Yalí",
  "Anorí",
  "Campamento",
  "Angostura",
  "Guadalupe",
  "Carolina del Príncipe",
  "Gómez Plata",
  "Yolombó",
  "Santo Domingo",
  "San Roque",
  "Maceo",
  "Puerto Berrío",
  "Puerto Nare",
  "Puerto Triunfo",
  "Cocorná",
  "San Carlos de Antioquia",
  "San Rafael",
  "Granada de Antioquia",
  "El Santuario",
  "Guarne",
  "La Ceja",
  "El Retiro",
  "Envigado",
  "Itagüí",
  "Sabaneta",
  "Medellín",
  "Bello",
  "Copacabana",
  "Girardota",
  "Barbosa",
  "Santo Domingo de Antioquia",
  "Donmatías",
  "Entrerríos",
  "Belmira",
  "Santa Rosa de Osos",
  "Yarumal",
  "Briceño",
  "Angostura de Antioquia",
  "Campamento de Antioquia",
  "Gómez Plata de Antioquia",
  "Guadalupe de Antioquia",
  "Cartagena de Indias",
  "Barranquilla",
  "Santa Marta",
  "Riohacha",
  "Valledupar",
  "Maracaibo",
  "La Guaira",
  "Puerto Cabello",
  "Coro",
  "Cumana",
  "Barcelona",
  "Puerto La Cruz",
  "Maturín",
  "Ciudad Bolívar",
  "Georgetown",
  "New Amsterdam",
  "Paramaribo",
  "Albina",
  "Cayenne",
  "Saint-Laurent-du-Maroni",
  "Kourou",
  "Sinnamary",
  "Iracoubo",
  "Mana",
  "Saint-Louis",
  "Awala-Yalimapo",
  "Grand-Santi",
  "Papaichton",
  "Maripasoula",
  "Saül",
  "Camopi",
  "Saint-Georges",
  "Ouanary",
  "Régina",
  "Roura",
  "Montsinéry-Tonnegrande",
  "Matoury",
  "Rémire-Montjoly",
  "Macouria"
];

export const ships = [
  "Santisima",
  "L'Ocean",
  "Santa Ana",
  "Victory",
  "DLC Victory",
  "Christian VII",
  "Bucentaure",
  "Redoutable",
  "Implacable",
  "St. Pavel",
  "Bellona",
  "3rd Rate (74)",
  "Wasa",
  "USS United States (previously Constitution)",
  "Constitution (previously classic)",
  "Rättvisan",
  "Agamemnon",
  "Leopard",
  "Indefatigable",
  "Ingermanland",
  "Wapen von Hamburg III",
  "Endymion",
  "Trincomalee",
  "Diana",
  "L'Hermione",
  "Santa Cecilia",
  "Essex",
  "Pirate Frigate(Cherubim)",
  "Belle Poule",
  "Frigate (Cherubim)",
  "LGV Refit",
  "Indiaman",
  "Surprise",
  "Renommee",
  "Le Gros Ventre",
  "Hercules",
  "Rattlesnake Heavy",
  "Pandora",
  "Le Requin",
  "Cerberus",
  "Niagara",
  "Mortar Brig",
  "Prince de Neufchatel",
  "Snow (Ontario)",
  "Mercury",
  "Rattlesnake",
  "Navy Brig (Fair American)",
  "Trader Snow",
  "Brig (Fair American)",
  "Pickle",
  "Yacht",
  "Privateer",
  "Cutter (Alert)",
  "Trader Lynx",
  "Lynx",
  "ADR",
  "Duke Of Kent",
  "San Pedro"
];

export const shipBRValues: Record<string, number> = {
  "Santisima": 278,
  "L'Ocean": 239,
  "Santa Ana": 225,
  "Victory": 216,
  "DLC Victory": 224,
  "Christian VII": 164,
  "Bucentaure": 161,
  "Redoutable": 148,
  "Implacable": 163,
  "St. Pavel": 150,
  "Bellona": 134,
  "3rd Rate (74)": 132,
  "Wasa": 125,
  "USS United States (previously Constitution)": 96,
  "Constitution (previously classic)": 96,
  "Rättvisan": 107,
  "Agamemnon": 114,
  "Leopard": 95,
  "Indefatigable": 79,
  "Ingermanland": 111,
  "Wapen von Hamburg III": 120,
  "Endymion": 85,
  "Trincomalee": 87,
  "Diana": 78,
  "L'Hermione": 72,
  "Santa Cecilia": 72,
  "Essex": 71,
  "Pirate Frigate(Cherubim)": 67,
  "Belle Poule": 65,
  "Frigate (Cherubim)": 66,
  "LGV Refit": 40,
  "Indiaman": 37,
  "Surprise": 64,
  "Renommee": 38,
  "Le Gros Ventre": 28,
  "Hercules": 58,
  "Rattlesnake Heavy": 32,
  "Pandora": 65,
  "Le Requin": 30,
  "Cerberus": 33,
  "Niagara": 25,
  "Mortar Brig": 15,
  "Prince de Neufchatel": 25,
  "Snow (Ontario)": 27,
  "Mercury": 25,
  "Rattlesnake": 22,
  "Navy Brig (Fair American)": 22,
  "Trader Snow": 26,
  "Brig (Fair American)": 20,
  "Pickle": 15,
  "Yacht": 15,
  "Privateer": 15,
  "Cutter (Alert)": 15,
  "Trader Lynx": 13,
  "Lynx": 13,
  "ADR": 143,
  "Duke Of Kent": 353,
  "San Pedro": 164
};

export const nations = [
  "Great Britain",
  "United States of America (USA)",
  "France",
  "Pirates",
  "Russia",
  "Sweden"
];

export const defaultClans = [
  "KRAKEN",
  "HYDRA",
  "LEVIATHAN",
  "MAELSTROM",
  "TEMPEST",
  "TSUNAMI",
  "RIPTIDE",
  "NEPTUNE",
  "POSEIDON",
  "TRITON"
];
