steps:
  # Build the frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'apps/frontend/Dockerfile'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/krakengaming/frontend:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_ENV=production'
      - '--build-arg'
      - 'NEXT_PUBLIC_DOMAIN=uwsgaming.org'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://uwsgaming-backend-1089166264123.us-central1.run.app'
      - '.'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/krakengaming/frontend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'uwsgaming-frontend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/krakengaming/frontend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port=3000'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--timeout=300'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_PUBLIC_ENV=production,NEXT_PUBLIC_DOMAIN=uwsgaming.org,NEXT_PUBLIC_API_URL=https://uwsgaming-backend-1089166264123.us-central1.run.app,NEXT_PUBLIC_APP_NAME=UWS Gaming,DATABASE_URL=postgresql://uwsgaming:Adm1nP@ss2024!@34.63.231.8:5432/uwsgaming,NEXTAUTH_URL=https://uwsgaming.org,NEXTAUTH_SECRET=uws-gaming-production-nextauth-secret-2024'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/krakengaming/frontend:latest'
