steps:
  # Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'apps/backend/Dockerfile'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/krakengaming/backend:latest'
      - '.'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/krakengaming/backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'uwsgaming-backend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/krakengaming/backend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port=4000'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--timeout=300'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=4000,DATABASE_URL=postgresql://uwsgaming:Adm1nP@ss2024!@34.63.231.8:5432/uwsgaming,JWT_SECRET=uws-gaming-production-jwt-secret-2024,CORS_ORIGIN=https://uwsgaming.org'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/krakengaming/backend:latest'
