version: '3.8'

# Note: Database is now Cloud SQL - no local PostgreSQL container needed
# This compose file is kept for potential Redis and other services

services:
  # Redis for caching and sessions (optional)
  redis:
    image: redis:7-alpine
    container_name: uwsgaming-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - uwsgaming-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Frontend (Next.js)
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    container_name: uwsgaming-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_ENV=local
      - NEXT_PUBLIC_DOMAIN=localhost:3000
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - NEXT_PUBLIC_BOT_URL=http://localhost:3001
      - DATABASE_URL=postgresql://uwsgaming:Adm1nP@ss2024!@34.135.241.34:5432/uwsgaming_prod
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - uwsgaming-network
    develop:
      watch:
        - action: sync
          path: ./apps/frontend/src
          target: /app/src
        - action: rebuild
          path: ./apps/frontend/package.json

  # Backend API (Fastify)
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    container_name: uwsgaming-backend
    ports:
      - "4000:4000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_PORT=4000
      - API_HOST=0.0.0.0
      - DATABASE_URL=postgresql://uwsgaming:Adm1nP@ss2024!@34.135.241.34:5432/uwsgaming_prod
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-for-local-development
      - API_CORS_ORIGIN=http://localhost:3000
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - uwsgaming-network
    develop:
      watch:
        - action: sync
          path: ./apps/backend/src
          target: /app/src
        - action: rebuild
          path: ./apps/backend/package.json

volumes:
  redis_data:
    driver: local

networks:
  uwsgaming-network:
    driver: bridge
